name: setup-gradle
description: 'Setup Gradle'
runs:
  using: composite

  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
        gradle-home-cache-cleanup: true
